algoritmo "ConversorDeMoeda"
// Função :
// Autor :
// Data : 17/06/2021
// Seção de Declarações 
var
Reais, Dolar: real

inicio
// Seção de Comandos 
EscrevaL ("Conversor de Real para Dólar (em 17/06/2021)")
         Escreva ("Quantos reais(R$) você possui? ")
         Leia (Reais)
         Dolar <- 5.03
         Escreva ("Com esse dinheiro você pode comprar", (Reais/Dolar), " Dolares.")
EscrevaL

fimalgoritmo
