algoritmo "DataDeAniversário"
// Função :
// Autor :
// Data : 17/06/2021
// Seção de Declarações 
var
   Ano_atual, Ano_nasci, idade: Inteiro


inicio
// Seção de Comandos 
EscrevaL ("Esqueceu sua idade? Vamos descobrir então!")
   Escreva ("Em que ano nós estamos? ")
   Leia (Ano_atual)
   Escreva ("Em que ano eu nasci? ")
   Leia (Ano_nasci)
   Idade <- Ano_atual - Ano_nasci
   Escreva ("Sua idade é", Idade, " anos")
   
fimalgoritmo
